FROM node:20-slim AS frontend

RUN mkdir -p build

WORKDIR /build

COPY ../frontend/package.json ./frontend/package-lock.json /build/

RUN npm install

COPY ./frontend /build

RUN npx tsc -p tsconfig.json

FROM node:20-slim AS results

WORKDIR /build

COPY ../results/package.json ../results/package-lock.json /build/

RUN npm install

COPY ../results /build

RUN npm run build

FROM nginxinc/nginx-unprivileged:1.26-alpine3.20-slim

COPY --from=frontend /build/assets /var/www/assets

COPY --from=frontend /build/*.html /var/www/

COPY ../docker/nginx.devel.conf etc/nginx/nginx.conf

COPY --from=results /build/dist/ChannelsDB /var/www/detail

CMD ["nginx", "-g", "daemon off;"]
