events {
    worker_connections 1024;
}

http {
    include mime.types;
    server {
        listen 80;
        root /var/www/;
        index index.html index.htm 

        gzip on;
        gzip_types text/plain text/xml text/css application/json application/javascript text/javascript;

        absolute_redirect off;

        rewrite  /detail/(.*)  /detail/$1 last;

        location = /api/ {
            proxy_pass http://be-channels:8000/;
        }

        location /api/ {
            proxy_pass http://be-channels:8000/api/;
        }

        location /openapi.json {
            proxy_pass http://be-channels:8000/openapi.json;
        }
    }   
}
