# TODO Add ids to loops that dont have identification.
# ============ CIF ============
CIF_ANNOTATION = """
loop_
_sb_ncbr_channel_annotation.id
_sb_ncbr_channel_annotation.channel_id
_sb_ncbr_channel_annotation.name
_sb_ncbr_channel_annotation.description
_sb_ncbr_channel_annotation.reference
_sb_ncbr_channel_annotation.reference_type
"""

CIF_CHANNEL = """
loop_
_sb_ncbr_channel.id
_sb_ncbr_channel.type # Path, Pore, etc
_sb_ncbr_channel.method # CSATunnel, etc
_sb_ncbr_channel.software # MOLE, Caver
_sb_ncbr_channel.auto # bool
_sb_ncbr_channel.cavity
"""

CIF_LAYER = """
loop_
_sb_ncbr_channel_layer.id
_sb_ncbr_channel_layer.channel_id
_sb_ncbr_channel_layer.order # order in channel
_sb_ncbr_channel_layer.min_radius
_sb_ncbr_channel_layer.min_free_radius
_sb_ncbr_channel_layer.start_distance
_sb_ncbr_channel_layer.end_distance
_sb_ncbr_channel_layer.local_minimum # bool
_sb_ncbr_channel_layer.bottleneck # bool
_sb_ncbr_channel_layer.charge
_sb_ncbr_channel_layer.numPositives
_sb_ncbr_channel_layer.numNegatives
_sb_ncbr_channel_layer.hydrophobicity
_sb_ncbr_channel_layer.hydropathy
_sb_ncbr_channel_layer.polarity
_sb_ncbr_channel_layer.mutability
"""

CIF_HET_RESIDUE = """
loop_
_sb_ncbr_channel_het_residue.id
_sb_ncbr_channel_het_residue.channel_id
_sb_ncbr_channel_het_residue.name
_sb_ncbr_channel_het_residue.sequence_number
_sb_ncbr_channel_het_residue.chain_id
_sb_ncbr_channel_het_residue.bottleneck # bool
"""

CIF_LAYER_RESIDUE = """
loop_
_sb_ncbr_channel_layer_residue.layer_id
_sb_ncbr_channel_layer_residue.residue_id
_sb_ncbr_channel_layer_residue.flow
_sb_ncbr_channel_layer_residue.backbone # bool
"""

CIF_PROFILE = """
loop_
_sb_ncbr_channel_profile.id
_sb_ncbr_channel_profile.channel_id
_sb_ncbr_channel_profile.radius
_sb_ncbr_channel_profile.free_radius
_sb_ncbr_channel_profile.distance
_sb_ncbr_channel_profile.T
_sb_ncbr_channel_profile.x
_sb_ncbr_channel_profile.y
_sb_ncbr_channel_profile.z
_sb_ncbr_channel_profile.charge
"""

# ============ CHIMERA ============
CHIMERA_HEADER = """\
import chimera


def add_atom(molecule, id, residue, x, y, z, radius):
    at = molecule.newAtom(id, chimera.Element("Tunn"))
    at.setCoord(chimera.Coord(x,y,z))
    at.radius = radius
    residue.addAtom(at)
"""

CHIMERA_FOOTER = """\
channel_object = chimera.Molecule()
channel_object.name = '{name}'
{name}(channel_object)
chimera.openModels.add([channel_object])
"""

CHIMERA_COLORS = [
    "red",
    "orange red",
    "orange",
    "yellow",
    "green",
    "forest green",
    "cyan",
    "light sea green",
    "blue",
    "cornflower blue",
    "medium blue",
    "purple",
    "hot pink",
    "magenta",
    "spring green",
    "plum",
    "sky blue",
    "goldenrod",
    "olive drab",
    "coral",
    "rosy brown",
    "slate gray",
]

# ============ PDB =============
PDB_HEADER = """\
REMARK 920
REMARK 920  This file was generated by MOLE 2 (https://mole.upol.cz, http://mole.chemi.muni.cz, version 2.5.17.4.24)
REMARK 920
REMARK 920  Please cite the following references when reporting the results using MOLE:
REMARK 920
REMARK 920  Sehnal D., Svobodova Varekova R., Berka K., Pravda L., Navratilova V., Banas P., Ionescu C.-M., Geidl S., Otyepka M., Koca J.:
REMARK 920  MOLE 2.0: Advanced Approach for Analysis of Biomacromolecular Channels. Journal of Cheminformatics 2013, 5:39. doi:10.1186/1758-2946-5-39
REMARK 920 
REMARK 920  and
REMARK 920
REMARK 920  Berka, K; Hanak, O; Sehnal, D; Banas, P; Navratilova, V; Jaiswal, D; Ionescu, C-M; Svobodova Varekova, R; Koca, J; Otyepka M:
REMARK 920  MOLEonline 2.0: Interactive Web-based Analysis of Biomacromolecular Channels.Nucleic Acid Research, 2012, doi:10.1093/nar/GKS363
REMARK 920
REMARK ATOM  NAM RES   TUNID     X      Y       Z       Distnm RadiusA
"""

PYMOL_COLORS = [
    "red",
    "green",
    "blue",
    "yellow",
    "violet",
    "cyan",
    "salmon",
    "lime",
    "pink",
    "slate",
    "magenta",
    "orange",
    "marine",
    "olive",
    "purple",
    "teal",
    "forest",
    "firebrick",
    "chocolate",
    "wheat",
    "white",
    "grey",
]

PYMOL_HEADER = """\
from pymol import cmd
from pymol.cgo import *
import chempy
def add_atom(model, name, vdw, x, y, z):
    a = chempy.Atom()
    a.name = name
    a.vdw = vdw
    a.coord = [x, y, z]
    model.atom.append(a)
"""

PYMOL_FOOTER = """\
    for a in range(len(model.atom) - 1):
        b = chempy.Bond()
        b.index = [a, a + 1]
        model.bond.append(b)
    cmd.set('surface_mode', 1)
    cmd.set('sphere_mode', 9)
    cmd.set('mesh_mode', 1)
    cmd.load_model(model, '{name}')
    cmd.hide('everything', '{name}')
    cmd.set('sphere_color', '{color}', '{name}')
    cmd.show('spheres', '{name}')
{name}()
cmd.group('Channels', [{name}], 'add')
"""

# ========= VMD ===============
VMD_HEADER = """\
package require http
# To run this script please run it in VMD as source script.vmd
# 
# If you find this tool useful for your work, please cite it as:
# Sehnal D, Svobodová Vařeková R, Berka K, Pravda L, Navrátilová V, Banáš P, Ionescu C-M, Otyepka M, Koča J: MOLE 2.0: advanced approach for analysis of biomacromolecular channels. J. Cheminform. 2013, 5:39.
# 
proc add_atom {id center r} {
 set atom [atomselect top "index $id"]
 $atom set {x y z}  $center
 $atom set radius $r
}
"""

VMD_CHANNEL_START = """\
set {name} [mol new atoms {num_atoms}]
mol top ${name}
animate dup ${name}
mol color ColorID {color_id}
mol representation VDW 1 60"""


VMD_CHANNEL_END = """\
mol delrep 0 ${name}
mol addrep ${name}
mol selection {{{{all}}}}
mol rename top {{{name}}}

"""
