name: channelsdb

services:
  pg-channels:
    image: postgres:14
    container_name: pg-channels
    environment:
      POSTGRES_NAME: channelsdb
      POSTGRES_USER: channelsdb
      POSTGRES_PASSWORD: admin
      POSTGRES_PORT: 5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "channelsdb", "-d", "channelsdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5435:5432"
    networks:
      channelsnet:
        ipv4_address: 172.20.0.4

  be-channels:
    build: ../backend
    container_name: be-channels
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --proxy-headers --workers 8
    environment:
      POSTGRES_NAME: channelsdb
      POSTGRES_USER: channelsdb
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: 172.20.0.4
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/opt/channelsdb
    logging:
      driver: journald
      options:
        tag: channelsdb-backend
    depends_on:
      pg-channels:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:8000/api/v1/health/ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      channelsnet:
        ipv4_address: 172.20.0.3


  fe-channels:
    container_name: fe-channels
    build: 
      context: ..
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./nginx.devel.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "${CHANNELSDB_PORT:-3000}:80"
    logging:
      driver: journald
      options:
        tag: channelsdb-web
    depends_on:
      be-channels:
        condition: service_healthy
        restart: true
    networks:
      channelsnet:
        ipv4_address: 172.20.0.2

networks:
  channelsnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/29 # 5 hosts + gateway
          gateway: 172.20.0.1