name: channelsdb

services:
  backend:
    build: ../backend
    container_name: backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --root-path /app --proxy-headers --workers 8
    volumes:
      - ${CHANNELSDB_DATA:-/data}:/data:ro
    logging:
      driver: journald
      options:
        tag: channelsdb-backend

  web:
    container_name: web
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./nginx.devel.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    ports:
      - "${CHANNELSDB_PORT:-80}:80"
    logging:
      driver: journald
      options:
        tag: channelsdb-web
