pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    server {
        client_body_temp_path /tmp/client_temp;
        proxy_temp_path       /tmp/proxy_temp_path;
        fastcgi_temp_path     /tmp/fastcgi_temp;
        uwsgi_temp_path       /tmp/uwsgi_temp;
        scgi_temp_path        /tmp/scgi_temp;
        
        listen 8080;
        root /var/www/;
        index index.html index.htm;

        gzip on;
        gzip_types text/plain text/xml text/css application/json application/javascript text/javascript;

        absolute_redirect off;

        location = /api/ {
            proxy_pass http://be-channels:8000/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            add_header "Access-Control-Allow-Origin" "*";
        }

        location /api/ {
            proxy_pass http://be-channels:8000/api/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            add_header "Access-Control-Allow-Origin" "*";
        }

        location /openapi.json {
            proxy_pass http://be-channels:8000/openapi.json;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            add_header "Access-Control-Allow-Origin" "*";
        }
    }
}
