import json
import os
import shutil
import subprocess as sub
from abc import ABC, abstractmethod

from defusedxml import ElementTree

from app.config import RELATIVE_MOLE_PATH
from app.database.models.method import Methods
from app.log import log


class MoleTemplate(ABC):
    TUNNEL_TYPE: str = ""
    METHOD_ID: Methods = None

    def __init__(self, worker_id: str, config_file: ElementTree) -> None:
        self.worker_id = worker_id

        self.config_dir = "./config"

        self.template_xml = config_file
        self.new_xml = self.template_xml

    @abstractmethod
    def configure(self, protein: str) -> None:
        """Method for preparing and creating configuration file based on template.

        This method needs to be implemented in child class.
        """

    def _finalize_configuration(self, protein: str) -> None:
        """Sets 'Input' and 'WorkingDirectory' keys in xml object and writes it into the file."""

        log.debug(
            f"WORKER {self.worker_id} {self.TUNNEL_TYPE.upper()} -- Finalizing configuration file."
        )
        self.new_xml.getroot().find("Input").text = self._get_source_path(protein)
        self.new_xml.getroot().find("WorkingDirectory").text = f"{os.getcwd()}"
        self.new_xml.write(f"./{protein}.xml", encoding="utf-8")

    def _get_source_path(self, protein: str) -> str:
        """Returns string representing path to a source file.

        Args:
            protein: name of entry file.
        Returns:
            string path
        """
        return f"./{protein}.cif"

    def create_source_file(self, protein: str, file: bytes) -> None:
        """Creates a source file for calculation.

        Args:
            protein: name of entry.
            file: file contents.
        """

        log.debug(
            f"WORKER {self.worker_id} {self.TUNNEL_TYPE.upper()} -- Creating a new file for entry: {protein}"
        )
        with open(self._get_source_path(protein), "wb") as binary_file:
            binary_file.write(file)

        log.debug(
            f"WORKER {self.worker_id} {self.TUNNEL_TYPE.upper()} -- File creation successfull for entry: {protein}"
        )

    def execute(self, protein: str) -> bool:
        """Runs mole command.

        Args:
            protein: name of protein
        Returns:

        """
        command = ["mono", RELATIVE_MOLE_PATH, f"./{protein}.xml"]
        result = sub.run(command, capture_output=True, text=True, check=True)

        if result.returncode != 0:
            log.error(
                f"WORKER {self.worker_id} {self.TUNNEL_TYPE.upper()} -- Mole software did not finish successfully -- code: {result.returncode}\n \nstdout: {result.stdout}\nstrerror: {result.stderr}"
            )
            return False

        log.info(
            f"WORKER {self.worker_id} {self.TUNNEL_TYPE.upper()} -- Mole software finished successfuly."
        )
        return True

    def retrieve(self) -> dict:
        """Loads JSON file with calculated data from Mole.

        Returns:
            'Tunnels' key from json file."""

        log.debug(
            f"WORKER {self.worker_id} {self.TUNNEL_TYPE.upper()} -- Reading JSON data."
        )
        file_path = "./json/data.json"

        with open(file_path, "r") as json_file:
            content = json.load(json_file)
            tunnels = content["Channels"]["Tunnels"]
            log.debug(
                f"WORKER {self.worker_id} {self.TUNNEL_TYPE.upper()} -- JSON data found."
            )

        return tunnels

    def cleanup(self):
        """Deletes files generated by Mole software, keeps folder structure intact if flag is not set.

        Args:
            include_workdir: flag to indicate if working directory should be deleted.
        """

        for item in os.listdir("./"):
            item_path = os.path.join("./", item)
            try:
                if os.path.isfile(item_path):
                    os.unlink(item_path)
                elif os.path.isdir(item_path):
                    shutil.rmtree(item_path)
            except Exception as e:
                log.error(
                    f"WORKER {self.worker_id} {self.TUNNEL_TYPE.upper()} -- Failed to delete {item_path}. Reason: {e}"
                )
        log.info(
            f"WORKER {self.worker_id} {self.TUNNEL_TYPE.upper()} -- Working directory has been deleted."
        )
